  export const data=[{
  Enrollment: 3117,
  HGOs: "PAN ISLAMIC TOURS & TRAVELS PVT LIMITED",
  CompanyNo: "0327",
  MunazimCompany: "AL MUGHANI MUNAZZAM PRIVATE LIMITED",
  Quota: 123,
  CEO: "MUHAMMAD SALMAN",
  Address: "OFFICE NO1, MAKKAH HEIGHTS, 11-ABBOTT ROAD, LAHORE",
  District: "LAHORE",
  Province: "PUNJAB",
  Directorate: "LAHORE",
  Phone: "0423-7414799",
  Mobile: "+923222214390",
  Email: "panislamic3117@gmail.com",
  Website: "https://www.panislamic.com.pk"
  },
  {
  Enrollment: 3331,
  HGOs: "MAYFAIR TRAVELLERS (PVT) LTD",
  CompanyNo: "0327",
  MunazimCompany: "AL MUGHANI MUNAZZAM PRIVATE LIMITED",
  Quota: 49,
  CEO: "GHULAM MURTAZA",
  Address: "11-GROUND FLOOR, MAKKAH HEIGHTS, 11-ABBOT ROAD, LAHORE",
  District: "LAHORE",
  Province: "PUNJAB",
  Directorate: "LAHORE",
  Phone: "0423-6366021",
  Mobile: "+923008067708",
  Email: "may_fair_travellers@hotmail.com",
  Website: "https://www.mayfairtravel.pk"
  },
  {
  Enrollment: 3344,
  HGOs: "SAFEENA-E-HARAM (PVT) LTD",
  CompanyNo: "0327",
  MunazimCompany: "AL MUGHANI MUNAZZAM PRIVATE LIMITED",
  Quota: 49,
  CEO: "ABDUL MANAN ANBALVI",
  Address: "LG F-7 CENTURY TOWER KALMA CHOWK GULBERG III LAHORE",
  District: "LAHORE",
  Province: "PUNJAB",
  Directorate: "LAHORE",
  Phone: "0423-5914036",
  Mobile: "+923214872799",
  Email: "umerarshad@live.com",
  Website: "https://www.dbgroup.pk/safina"
  },
  {
  Enrollment: 3334,
  HGOs: "AM HAFIZ TRAVEL & TOUR (PVT) LTD",
  CompanyNo: "0327",
  MunazimCompany: "AL MUGHANI MUNAZZAM PRIVATE LIMITED",
  Quota: 49,
  CEO: "HAFIZ AMANULLAH",
  Address: "1ST FLOOR HASSAN ARCADE, 19-A ABBOT ROAD, OPPOSITE PTV, LAHORE",
  District: "LAHORE",
  Province: "PUNJAB",
  Directorate: "LAHORE",
  Phone: "0423-6302035",
  Mobile: "+923218401171",
  Email: "hafiz_travel@yahoo.com",
  Website: "https://www.bestumrahhajj.com"
  },
  {
  Enrollment: 3330,
  HGOs: "KARWAN-E-ZAITOON TRAVEL & TOUR (PVT) LTD",
  CompanyNo: "0327",
  MunazimCompany: "AL MUGHANI MUNAZZAM PRIVATE LIMITED",
  Quota: 49,
  CEO: "SHAHID AMIN",
  Address: "G-13, HILL VIEW ARCADE, 5-DAVIS ROAD, LAHORE",
  District: "LAHORE",
  Province: "PUNJAB",
  Directorate: "LAHORE",
  Phone: "0423-6292967",
  Mobile: "+923004281421",
  Email: "karwanezaitoon_intl@yahoo.com",
  Website: "https://www.karwanezaitoon.com"
  },
  {
  Enrollment: 3328,
  HGOs: "FAQEER ULLAH (PVT) LTD",
  CompanyNo: "0327",
  MunazimCompany: "AL MUGHANI MUNAZZAM PRIVATE LIMITED",
  Quota: 49,
  CEO: "MUHAMMAD AKBAR BHATTI",
  Address: "G-30, SHIMLA TOWER, 5-DAVIS ROAD, LAHORE",
  District: "LAHORE",
  Province: "PUNJAB",
  Directorate: "LAHORE",
  Phone: "0423-6370049",
  Mobile: "+923004236168",
  Email: "faqeerullah@hotmail.com",
  Website: "https://www.faqeerullah.com"
  },
  {
  Enrollment: 3340,
  HGOs: "NATIONAL AIR EXPRESS TRAVEL SERVICES (PVT) LTD",
  CompanyNo: "0327",
  MunazimCompany: "AL MUGHANI MUNAZZAM PRIVATE LIMITED",
  Quota: 49,
  CEO: "MASOOD SADIQ",
  Address: "G-5 HILLVIEW ARCADE, 5 DAVIS ROAD, LAHORE",
  District: "LAHORE",
  Province: "PUNJAB",
  Directorate: "LAHORE",
  Phone: "0336-4448666",
  Mobile: "+923334216932",
  Email: "omer@nationalairexpress.net",
  Website: "https://www.nationalairexpress.net"
  },
  {
  Enrollment: 3325,
  HGOs: "EVERLUCK TRAVELLING & TOURS (PVT) LTD",
  CompanyNo: "0327",
  MunazimCompany: "AL MUGHANI MUNAZZAM PRIVATE LIMITED",
  Quota: 49,
  CEO: "FAIZAN",
  Address: "FIRST FLOOR, 149-A,H-MALL, SHALIMAR LINK ROAD,LAHORE",
  District: "LAHORE",
  Province: "PUNJAB",
  Directorate: "LAHORE",
  Phone: "0092-3234107384",
  Mobile: "+923234107384",
  Email: "everlucktraveling@yahoo.com",
  Website: "https://www.everluckhajj.com"
  },
  {
  Enrollment: 6148,
  HGOs: "KARWAN-E-HERMAIN TOGERVI TRAVELS (PVT) LTD",
  CompanyNo: "0327",
  MunazimCompany: "AL MUGHANI MUNAZZAM PRIVATE LIMITED",
  Quota: 49,
  CEO: "ZAFAR IQBAL",
  Address: "MAIN BAZAR, KOLHO MECLEOD GUNJ, BAHAWALNAGAR",
  District: "BAHAWAL NAGAR",
  Province: "PUNJAB",
  Directorate: "MULTAN",
  Phone: "0632-760683",
  Mobile: "+923334159683",
  Email: "khtogervitravels@gmail.com",
  Website: "https://zafargroup.com.pk"
  }
]